CREATE TABLE IF NOT EXISTS user_fidyah (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone_num VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ALL_USER_IDX ON user_fidyah (id, name, email, phone_num);

CREATE INDEX ID_NAME_IDX ON user_fidyah (id, name);

CREATE INDEX EMAIL_IDX ON user_fidyah (email);

CREATE TABLE IF NOT EXISTS rate_fidyah (
  id SERIAL PRIMARY KEY,
  rate INT NOT NULL
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);